version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: favourites
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: favourites

	favourites:
		build: .
		image: chamaconekt/favourites
		links:
		- postgres
		container_name: favourites
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- favourites
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/favourites-nginx/nginx.conf
		depends_on:
			- favourites
		ports:
			- 80:80
		volumes_from:
			- favourites

volumes:
	favourites-static-files:
		driver:local